"""add_user_github_installations_table

Revision ID: 5abfdeaae98a
Revises: c4d8f2a91b3e
Create Date: 2026-06-10 21:49:57.125823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abfdeaae98a'
down_revision: Union[str, Sequence[str], None] = 'c4d8f2a91b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
