"""initial

Revision ID: eba979457564
Revises: 
Create Date: 2026-04-03 16:31:32.510207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba979457564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYING_OPENSTACK', 'DEPLOYING_AWS', 'RUNNING', 'DEGRADED', 'ROLLING_BACK', 'FAILED', 'DELETING', 'DELETED', name='deploymentstatus'), nullable=False),
    sa.Column('step_message', sa.String(length=255), nullable=False),
    sa.Column('os_vm_db1_id', sa.String(length=100), nullable=True),
    sa.Column('os_vm_db2_id', sa.String(length=100), nullable=True),
    sa.Column('os_vm_db1_ip', sa.String(length=50), nullable=True),
    sa.Column('os_vm_db2_ip', sa.String(length=50), nullable=True),
    sa.Column('aws_asg_name', sa.String(length=100), nullable=True),
    sa.Column('aws_alb_dns', sa.String(length=255), nullable=True),
    sa.Column('aws_instance_ids', sa.Text(), nullable=True),
    sa.Column('app_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
