{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arcl-cmp.fullname" . }}-backend-data
  labels:
    {{- include "arcl-cmp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.persistence.backend.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.backend.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arcl-cmp.fullname" . }}-backend-db
  labels:
    {{- include "arcl-cmp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.persistence.backend.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
