{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arcl-cmp.fullname" . }}-secret
  labels:
    {{- include "arcl-cmp.labels" . | nindent 4 }}
type: Opaque
stringData:
  os-auth-url: {{ .Values.secrets.openstack.authUrl | quote }}
  # ... le reste de ton fichier
{{- end }}
