apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arcl-cmp.fullname" . }}-secret
  labels:
    {{- include "arcl-cmp.labels" . | nindent 4 }}
type: Opaque
stringData:
  os-auth-url: {{ .Values.secrets.openstack.authUrl | quote }}
  os-username: {{ .Values.secrets.openstack.username | quote }}
  os-password: {{ .Values.secrets.openstack.password | quote }}
  os-project-name: {{ .Values.secrets.openstack.projectName | quote }}
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | quote }}
